version: "3.9"
services:
  localstack:
    image: localstack/localstack:s3-latest
    container_name: localstack
    network_mode: bridge
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - 4566:4566
    volumes:
      - ./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
